const THEM_SV = "THEM_SV";
const GET_COURSE = "GET_COURSE";
const GET_COURSE_BYID = "GET_COURSE_BYID";
const POST_USER = "POST_USER";
const Sign = "Sign";
const KEO_BUA_BAO = "KEO_BUA_BAO";
const PLAY_KEO_BUA_BAO = "PLAY_KEO_BUA_BAO";
const RESULT_KEO_BUA_BAO = "RESULT_KEO_BUA_BAO";
const DAT_GHE_TICKET = "DAT_GHE_TICKET";
const HUY_GHE = "HUY_GHE";
const TAKS_DOING = "TAKS_DOING";
const ADD_TAKS = "ADD_TAKS";
const EDIT_TAKS = "EDIT_TAKS";
const CHECK_TAKS = "CHECK_TAKS";
const UPDATE_TAKS = "UPDATE_TAKS";
const DELETE_TAKS_TODO = "DELETE_TAKS";
const DELETE_TAKS_COMPLETE = "DELETE_TAKS_COMPLETE";
export {
  PLAY_KEO_BUA_BAO,
  THEM_SV,
  GET_COURSE,
  GET_COURSE_BYID,
  POST_USER,
  Sign,
  KEO_BUA_BAO,
  RESULT_KEO_BUA_BAO,
  DAT_GHE_TICKET,
  HUY_GHE,
  TAKS_DOING,
  ADD_TAKS,
  EDIT_TAKS,
  CHECK_TAKS,
  DELETE_TAKS_TODO,
  UPDATE_TAKS,
  DELETE_TAKS_COMPLETE,
};
